### PR TITLE
created convert module

### PR DESCRIPTION
**Pull request by John-Ragland**
I created a module to convert DAS data
The first function converts h5 (formatted for OOI DAS South Transmit fiber), to zarr using xarray.

I also included a batch script to download all of the OOI South Tx files to local disk.

### CODE REVIEW

**Comment by John-Ragland** [comment]
@niyiyu, I added a few other small changes. Any thoughts on the modules section of the code organization?

**Comment by niyiyu** [comment]
Hi John,

Sorry for this late reply as I am taking a time off in Mexico. Packaging the codes into a module for data conversion is great! I am thinking about having a client to make the reading easier for seismology use case. After merging the `module`, I might put it into a DASStore source directory as a submodule. I am still thinking about the structure, backend, and other utils. What do you think?

Cheers,
Yiyu

**Comment by John-Ragland** [comment]
No worries!
What do you mean by the client for the seismology use case?

As for how the package is organized, I'm good with anything. Since it might be a good idea to talk through the different use cases and goals for the package I've opened an issue #3 where we can discuss this 👍

**Comment by John-Ragland** [comment]
Just discovered that h5 file must have integer number of chunks in append dimensions for modules.convert.h52zarr_xarray to work. When @aishwarya-singh25 and I were converting h5 files from an experiment, we discovered that the interrogator was saving some files with different time dimensions. We're currently unsure what is causing this, but ultimately we'll want to be able to catch these errors.

**Comment by John-Ragland** [comment]
I added some TODO statements, but I don't think we need to add this feature for the PR

**Comment by niyiyu** [comment]
Regarding the chunking, yes, some h5 files are using a weird (743, 88) chunk size. I think it wont be a problem if the array is loaded into memory and write into object storage later, which contain no prior chunking information.

**Pull request merged**
